# Generated by Django 2.0.7 on 2018-08-08 20:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Loko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.CharField(max_length=255)),
                ('stavka_za_km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Probeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_count', models.IntegerField()),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1851), django.core.validators.MaxValueValidator(9999)])),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Filial')),
                ('loko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Loko')),
            ],
        ),
    ]
