# Generated by Django 2.0.7 on 2018-08-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_auto_20180813_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loko',
            name='stavka_za_km',
            field=models.FloatField(),
        ),
    ]
